# Generated by Django 2.2.4 on 2019-08-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_auto_20190827_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesses',
            name='listing',
            field=models.CharField(default='AAPL', max_length=25),
        ),
        migrations.AlterField(
            model_name='businesses',
            name='stock_code',
            field=models.CharField(default='AAPL', max_length=25),
        ),
        migrations.AlterField(
            model_name='data',
            name='employees',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='data',
            name='products',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='data',
            name='sales',
            field=models.CharField(max_length=12),
        ),
    ]
