# Generated by Django 2.2.4 on 2019-08-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_auto_20190827_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='employees',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='data',
            name='products',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='data',
            name='sales',
            field=models.CharField(max_length=45),
        ),
    ]
