# Generated by Django 2.2.4 on 2019-08-27 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_auto_20190827_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business', to='user_app.Businesses'),
        ),
    ]
