# Generated by Django 2.2.4 on 2019-08-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_auto_20190827_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='retirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_one', models.CharField(max_length=45)),
                ('asset_two', models.CharField(max_length=45)),
                ('asset_three', models.CharField(max_length=45)),
                ('asset_one_percentage', models.IntegerField()),
                ('asset_two_percentage', models.IntegerField()),
                ('asset_three_percentage', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
