# Generated by Django 2.2.4 on 2019-08-28 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_retirement_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retirement',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='user_retire', to='user_app.Users'),
        ),
    ]
